server:
  port: "8080"
  mode: debug

database:
  dsn: "root:password@tcp(mysql:3306)/tokenfactory?parseTime=true&charset=utf8mb4"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

jwt:
  access_secret: "change-me-access-secret-key-32chars"
  refresh_secret: "change-me-refresh-secret-key-32chars"
  access_ttl: 900
  refresh_ttl: 604800

security:
  credential_key: ""
  cap_siteverify_url: "http://host.docker.internal:3210/local-dev/siteverify"
  cap_secret: "DEMO_REPLACE_ME_CAP_SITE_SECRET_32_CHARS"
